echo Executing NeXTTool to upload ../../ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
wineconsole /cygdrive/C/cygwin/nexttool/NeXTTool.exe /COM=usb -firmware=../../ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
